version: '3.7'
services:
  jupyter:
    image: jupyter/scipy-notebook
    volumes:
      - /home/rafael/RAFAEL/git/IA006C-MachineLearning/final\ project:/opt/final\ project  
      #- /root/ito/IA006C-MachineLearning/final\ project:/opt/final\ project  
    ports:
      - "10000:8888"
    networks:
      hostnet: {}
    dns:
      - 10.0.0.71
      - 10.0.0.72
    deploy:
      placement:
        constraints:
          - node.hostname == lnls136
          #- node.hostname == LA-RaCtrl-CO-Srv-1
      replicas: 1
      restart_policy:
        condition: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

networks:
  hostnet:
    external: true
    name: host
